name: Trigger Copado Robotic Testing Job

on:
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  trigger-test:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CRT Job
        run: |
          curl -v -X POST "https://api.eu-robotic.copado.com/pace/v4/projects/${PROJECT_ID}/jobs/${JOB_ID}/builds" \
            -H "Authorization: Bearer ${{ secrets.CRT_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"projectId\": \"${{ secrets.CRT_PROJECT_ID }}\",
              \"testJobId\": \"${{ secrets.CRT_TEST_JOB_ID }}\"
            }"
